`numpy.arrar`是python处理图像的基础


## 2.1 图像的基本表示方法 && 2.2 像素处理
- 二值图像 (0 or 1)
- 灰度图像(0 ~ 255)
- 彩色图像

In [2]:
import cv2 as cv
import numpy as np

img = np.zeros((8, 8), dtype=np.uint8)
print("img = \n", img)

cv.imshow("one", img)
print("读取像素点img[0, 3] = ", img[0, 3])
img[0, 3] = 255

print("\n修改后img = \n", img)
print("读取像素点img[0, 3] = ", img[0, 3])

cv.imshow("two", img)
cv.waitKey()
cv.destroyAllWindows()


img = 
 [[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
读取像素点img[0, 3] =  0

修改后img = 
 [[  0   0   0 255   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]]
读取像素点img[0, 3] =  255


In [3]:
img = cv.imread("../resource/lena.bmp", 0)

cv.imshow("before", img)

for i in range(10, 100):
    for j in range(80, 100):
        img[i, j] = 255

cv.imshow("after", img)
cv.waitKey()
cv.destroyAllWindows()


In [4]:
# 蓝色通道值
blue = np.zeros((300, 300, 3), dtype=np.uint8)
blue[:, :, 0] = 255

print("blue = \n", blue)
cv.imshow("blue", blue)

# 绿色通道值
green = np.zeros((300, 300, 3), dtype=np.uint8)
green[:, :, 1] = 255

print("green = \n", green)
cv.imshow("green", green)

# 红色通道值
red = np.zeros((300, 300, 3), dtype=np.uint8)
red[:, :, 2] = 255

print("red = \n", red)
cv.imshow("red", red)

cv.waitKey()
cv.destroyAllWindows()


blue = 
 [[[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 ...

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]]
green = 
 [[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0 255   0]
 

In [5]:
img = np.zeros((300, 300, 3), dtype=np.uint8)
img[:, 0:100, 0] = 255
img[:, 100:200, 1] = 255
img[:, 200:300, 2] = 255

cv.imshow("img", img)
cv.waitKey()
cv.destroyAllWindows()


In [6]:
img = np.zeros((2, 4, 3), np.uint8)
print("img = \n", img)

print("img[0, 3] = ", img[0, 3])
print("img[1, 2, 2] = ", img[1, 2, 2])
img[0, 3] = 255  # 第0行 第3列 的BGR通道的三个像素点
img[0, 0] = [66, 77, 88]  # 第0行 第0列 的BGR三个像素点
img[1, 1, 1] = 3
img[1, 2, 2] = 4
img[0, 2, 0] = 5
print("img = \n", img)
print("img[1, 2, 2] = ", img[1, 2, 2])


img = 
 [[[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
img[0, 3] =  [0 0 0]
img[1, 2, 2] =  0
img = 
 [[[ 66  77  88]
  [  0   0   0]
  [  5   0   0]
  [255 255 255]]

 [[  0   0   0]
  [  0   3   0]
  [  0   0   4]
  [  0   0   0]]]
img[1, 2, 2] =  4


In [7]:
img = cv.imread("../resource/lena.png")
cv.imshow("before", img)

print("访问img[0,0]=", img[0, 0])
print("访问img[0,0,0]=", img[0, 0, 0])
print("访问img[0,0,1]=", img[0, 0, 1])
print("访问img[0,0,2]=", img[0, 0, 2])
print("访问img[50,0]=", img[50, 0])
print("访问img[100,0]=", img[100, 0])

# 区域1
for i in range(0, 50):
    for j in range(0, 100):
        for k in range(0, 3):
            img[i, j, k] = 255  # 白色

# 区域2
for i in range(50, 100):
    for j in range(0, 100):
        img[i, j] = [128, 128, 128]  # 灰色

# 区域3
for i in range(100, 150):
    for j in range(0, 100):
        img[i, j] = 0  # 黑色

cv.imshow("after", img)

print("修改后img[0,0]=", img[0, 0])
print("修改后img[0,0,0]=", img[0, 0, 0])
print("修改后img[0,0,1]=", img[0, 0, 1])
print("修改后img[0,0,2]=", img[0, 0, 2])
print("修改后img[50,0]=", img[50, 0])
print("修改后img[100,0]=", img[100, 0])

cv.waitKey()
cv.destroyAllWindows()


访问img[0,0]= [123 154 218]
访问img[0,0,0]= 123
访问img[0,0,1]= 154
访问img[0,0,2]= 218
访问img[50,0]= [106 153 223]
访问img[100,0]= [ 42  57 119]
修改后img[0,0]= [255 255 255]
修改后img[0,0,0]= 255
修改后img[0,0,1]= 255
修改后img[0,0,2]= 255
修改后img[50,0]= [128 128 128]
修改后img[100,0]= [0 0 0]


## 2.3 使用np.array访问像素

item() 和 itemset() 函数来访问和修改像素值，而且这两个函数经过了优化处理，能够大幅度提升处理效率

访问及修改像素点时，使用np.array提供的函数要比直接索引快

- item(col, row): 高效地访问图像的像素点

- itemset(索引值, 新值): 修改像素值

In [8]:
img = np.random.randint(10, 99, size=(5, 5), dtype=np.uint8)
print("img = \n", img)
print("读取像素点img.item(3, 2) =", img.item(3, 2))

img.itemset((3, 2), 255)
print("修改后img=\n", img)
print("修改后像素点img.item(3, 2) =", img.item(3, 2))


img = 
 [[47 58 26 24 37]
 [85 11 67 32 39]
 [34 64 47 75 59]
 [56 77 17 42 64]
 [27 52 28 91 63]]
读取像素点img.item(3, 2) = 17
修改后img=
 [[ 47  58  26  24  37]
 [ 85  11  67  32  39]
 [ 34  64  47  75  59]
 [ 56  77 255  42  64]
 [ 27  52  28  91  63]]
修改后像素点img.item(3, 2) = 255


In [9]:
# 生成一个灰度图像,像素值均为随机数
img = np.random.randint(0, 256, size=[512, 512], dtype=np.uint8)
cv.imshow("demo", img)
cv.waitKey()
cv.destroyAllWindows()


In [10]:
img = cv.imread("../resource/lena.bmp", 0)

# 测试读取、修改单个像素值
print("读取像素点img.item(3, 2) =", img.item(3, 2))
img.itemset((3, 2), 255)
print("修改后像素点img.item(3, 2) =", img.item(3, 2))

# 测试修改一个区域的像素值
cv.imshow("before", img)
for i in range(10, 100):
    for j in range(80, 100):
        img.itemset((i, j), 255)

cv.imshow("after", img)
cv.waitKey()
cv.destroyAllWindows()


读取像素点img.item(3, 2) = 159
修改后像素点img.item(3, 2) = 255


- item 和 itemset() 也可访问和修改彩色图像的像素值,不同之处在于需要补充通道信息

针对RGB图像的访问,必须同时指定行\列\通道
```python
item(行, 列, 通道)

itemset(三元组索引值, 新值)
```

In [11]:
img = np.random.randint(10, 99, size=[2, 4, 3], dtype=np.uint8)
print("img = \n", img)
print("读取像素点img[1, 2, 0] =", img.item(1, 2, 0))
print("读取像素点img[0, 2, 1] =", img.item(0, 2, 1))
print("读取像素点img[1, 0, 2] =", img.item(1, 0, 2))

img.itemset((1, 2, 0), 255)
img.itemset((0, 2, 1), 255)
img.itemset((1, 0, 2), 255)
print("修改后img = \n", img)
print("修改后像素点img[1,2,0] =", img.item(1, 2, 0))
print("修改后像素点img[0,2,1] =", img.item(0, 2, 1))
print("修改后像素点img[1,0,2] =", img.item(1, 0, 2))


img = 
 [[[30 16 69]
  [72 42 66]
  [46 73 41]
  [35 17 45]]

 [[59 66 88]
  [77 86 79]
  [61 64 31]
  [31 15 73]]]
读取像素点img[1, 2, 0] = 61
读取像素点img[0, 2, 1] = 73
读取像素点img[1, 0, 2] = 88
修改后img = 
 [[[ 30  16  69]
  [ 72  42  66]
  [ 46 255  41]
  [ 35  17  45]]

 [[ 59  66 255]
  [ 77  86  79]
  [255  64  31]
  [ 31  15  73]]]
修改后像素点img[1,2,0] = 255
修改后像素点img[0,2,1] = 255
修改后像素点img[1,0,2] = 255


In [12]:
img = np.random.randint(0, 256, size=[256, 256, 3], dtype=np.uint8)
cv.imshow("demo", img)
cv.waitKey()
cv.destroyAllWindows()


In [13]:
img = cv.imread("../resource/lena.png")
cv.imshow("before", img)
print("访问img.item(0,0,0)=", img.item(0, 0, 0))
print("访问img.item(0,0,1)=", img.item(0, 0, 1))
print("访问img.item(0,0,2)=", img.item(0, 0, 2))

for i in range(0, 50):
    for j in range(0, 100):
        for k in range(0, 3):
            img.itemset((i, j, k), 255)  # 白色
cv.imshow("after", img)

print("修改后img.item(0,0,0)=", img.item(0, 0, 0))
print("修改后img.item(0,0,1)=", img.item(0, 0, 1))
print("修改后img.item(0,0,2)=", img.item(0, 0, 2))

cv.waitKey()
cv.destroyAllWindows()

访问img.item(0,0,0)= 123
访问img.item(0,0,1)= 154
访问img.item(0,0,2)= 218
修改后img.item(0,0,0)= 255
修改后img.item(0,0,1)= 255
修改后img.item(0,0,2)= 255


## 2.4 ROI

针对图像的某一特定的区域感兴趣,被称为感兴趣区域(Region of Interest, ROI). 设定ROI后, 可以针对该区域进行整体操作.

In [14]:
# 提取lena的face ROI
img = cv.imread("../resource/lena.png")
cv.imshow("lena.png", img)

face = img[200:400, 250:350]

cv.imshow("face.png", face)
cv.waitKey()
cv.destroyAllWindows()

In [15]:
# 对face 打马
face = np.random.randint(0, 256, (180, 100, 3))
img[220: 400, 250:350] = face

cv.imshow("result", img)
cv.waitKey()
cv.destroyAllWindows()

In [16]:
lena = cv.imread("../resource/lena.png")
dollor = cv.imread("../resource/dollor.bmp")
cv.imshow("dollor", dollor)
cv.imshow("lena", lena)

lena_face = lena[220:400, 250:350]
dollor[160:340, 200:300] = lena_face

cv.imshow("result", dollor)
cv.waitKey()
cv.destroyAllWindows()


## 2.5 通道操作
在OpenCV中, 是按照 B  G  R 通道存储的

In [17]:
lena = cv.imread("../resource/lena.png")
cv.imshow("lena1", lena)
b = lena[:, :, 0]  # B 通道
g = lena[:, :, 1]  # G 通道
r = lena[:, :, 2]  # R 通道
cv.imshow("b", b)
cv.imshow("g", g)
cv.imshow("r", r)

lena[:, :, 0] = 0  # 将B通道设置为0
cv.imshow("lenab0", lena)

lena[:, :, 1] = 0  # 将G通道设置为0
cv.imshow("lenab0g0", lena)

cv.waitKey()
cv.destroyAllWindows()


In [19]:
lena_color = cv.imread("../resource/lena.png")

b, g, r = cv.split(lena_color)

cv.imshow("B", b)
cv.imshow("G", g)
cv.imshow("R", r)

cv.waitKey()
cv.destroyAllWindows()


In [21]:
bgr = cv.merge([b, g, r])
rgb = cv.merge([r, g, b])

cv.imshow("lena", lena_color)
cv.imshow("bgr", bgr)
cv.imshow("rgb", rgb)

cv.waitKey()
cv.destroyAllWindows()


## 2.6 获取图像属性
* shape: 如果是彩色图像: 返回行, 列, 通道数；如果是灰度图像:返回行, 列
* size: 返回图像的像素数目. 值 = 行 * 列 * 通道数
* dtype: 返回图像的数据类型

In [23]:
gray = cv.imread("../resource/lena.bmp", 0)
print("图像gray属性：")
print("gray.shape =", gray.shape)
print("gray.size =", gray.size)
print("gray.dtype =", gray.dtype)

color = cv.imread("../resource/lena.png")
print("图像color属性：")
print("color.shape =", color.shape)
print("color.size =", color.size)
print("color.dtype =", color.dtype)


图像gray属性：
gray.shape = (256, 256)
gray.size = 65536
gray.dtype = uint8
图像color属性：
color.shape = (512, 512, 3)
color.size = 786432
color.dtype = uint8
