`numpy.arrar`是python处理图像的基础

In [2]:
import cv as cv
import numpy as np

img = np.zeros((8, 8), dtype=np.uint8)
print("img = \n", img)

cv.imshow("one", img)
print("读取像素点img[0, 3] = ", img[0, 3])
img[0, 3] = 255

print("\n修改后img = \n", img)
print("读取像素点img[0, 3] = ", img[0, 3])

cv.imshow("two", img)
cv.waitKey()
cv.destroyAllWindows()

img = 
 [[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
读取像素点img[0, 3] =  0
修改后img = 
 [[  0   0   0 255   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]]
读取像素点img[0, 3] =  255


In [3]:
img = cv.imread("../resource/lena.bmp", 0)

cv.imshow("before", img)

for i in range(10, 100):
    for j in range(80, 100):
        img[i, j] = 255

cv.imshow("after", img)
cv.waitKey()
cv.destroyAllWindows()


In [4]:
# 蓝色通道值
blue = np.zeros((300, 300, 3), dtype=np.uint8)
blue[:, :, 0] = 255

print("blue = \n", blue)
cv.imshow("blue", blue)

# 绿色通道值
green = np.zeros((300, 300, 3), dtype=np.uint8)
green[:, :, 1] = 255

print("green = \n", green)
cv.imshow("green", green)

# 红色通道值
red = np.zeros((300, 300, 3), dtype=np.uint8)
red[:, :, 2] = 255

print("red = \n", red)
cv.imshow("red", red)

cv.waitKey()
cv.destroyAllWindows()

blue = 
 [[[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 ...

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]]
green = 
 [[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0 255   0]
 

In [7]:
img = np.zeros((300, 300, 3), dtype=np.uint8)
img[:, 0:100, 0] = 255
img[:, 100:200, 1] = 255
img[:, 200:300, 2] = 255

cv.imshow("img", img)
cv.waitKey()
cv.destroyAllWindows()

In [11]:
img = np.zeros((2, 4, 3), np.uint8)
print("img = \n", img)

print("img[0, 3] = ", img[0, 3])
print("img[1, 2, 2] = ", img[1, 2, 2])
img[0, 3] = 255  # 第0行 第3列 的BGR通道的三个像素点
img[0, 0] = [66, 77, 88]  # 第0行 第0列 的BGR三个像素点
img[1, 1, 1] = 3
img[1, 2, 2] = 4
img[0, 2, 0] = 5
print("img = \n", img)
print("img[1, 2, 2] = ", img[1, 2, 2])

img = 
 [[[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
img[0, 3] =  [0 0 0]
img[1, 2, 2] =  0
img = 
 [[[ 66  77  88]
  [  0   0   0]
  [  5   0   0]
  [255 255 255]]

 [[  0   0   0]
  [  0   3   0]
  [  0   0   4]
  [  0   0   0]]]
img[1, 2, 2] =  4


In [12]:
img = cv.imread("../resource/lena.png")
cv.imshow("before", img)

print("访问img[0,0]=", img[0, 0])
print("访问img[0,0,0]=", img[0, 0, 0])
print("访问img[0,0,1]=", img[0, 0, 1])
print("访问img[0,0,2]=", img[0, 0, 2])
print("访问img[50,0]=", img[50, 0])
print("访问img[100,0]=", img[100, 0])

# 区域1
for i in range(0, 50):
    for j in range(0, 100):
        for k in range(0, 3):
            img[i, j, k] = 255  # 白色

# 区域2
for i in range(50, 100):
    for j in range(0, 100):
        img[i, j] = [128, 128, 128]  # 灰色

# 区域3
for i in range(100, 150):
    for j in range(0, 100):
        img[i, j] = 0  # 黑色

cv.imshow("after", img)

print("修改后img[0,0]=", img[0, 0])
print("修改后img[0,0,0]=", img[0, 0, 0])
print("修改后img[0,0,1]=", img[0, 0, 1])
print("修改后img[0,0,2]=", img[0, 0, 2])
print("修改后img[50,0]=", img[50, 0])
print("修改后img[100,0]=", img[100, 0])

cv.waitKey()
cv.destroyAllWindows()

访问img[0,0]= [123 154 218]
访问img[0,0,0]= 123
访问img[0,0,1]= 154
访问img[0,0,2]= 218
访问img[50,0]= [106 153 223]
访问img[100,0]= [ 42  57 119]
修改后img[0,0]= [255 255 255]
修改后img[0,0,0]= 255
修改后img[0,0,1]= 255
修改后img[0,0,2]= 255
修改后img[50,0]= [128 128 128]
修改后img[100,0]= [0 0 0]
